eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:9000/eureka/
  instance:
    hostname: localhost
    
payment-service:
  endpoints:
    endpoint:
      uri: http://payment-service/payments/save
order-service:
  endpoints:
    endpoint:
      uri: http://order-service/orders/book    
      
      
insurance:
  endpoint: 
    uri: http://localhost:8000/insurance-service/plans12345
  
limits-service:
  minimum: 8
  maximum: 8888
