eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:9000/eureka/
  instance:
    hostname: localhost
    
payment-service:
  endpoints:
    endpoint:
      uri: http://payment-service/payments/save
order-service:
  endpoints:
    endpoint:
      uri: http://order-service/orders/book    
      
      
insurance:
  endpoint: 
    uri: http://localhost:8000/insurance-service/plans12345
  
limits-service:
  minimum: 9
  maximum: 99
  
#mysql configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: admin
 
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1 
  cloud:
    config:
      uri: http://localhost:8888
      
server:
  port: 9090
#Eureka server configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
#hystrix dashboard
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
          
